# Generated by Django 2.2.7 on 2020-01-23 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('call', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mill',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('queue', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('sprice', models.IntegerField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ownermill',
            fields=[
                ('oid', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreLevel',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wakerfarmer.Farmer')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wakerfarmer.ScoreLevel')),
                ('mill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wakerfarmer.Mill')),
            ],
        ),
        migrations.CreateModel(
            name='Carqueue',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('queue', models.IntegerField(blank=True, null=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wakerfarmer.Farmer')),
                ('mill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wakerfarmer.Mill')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wakerfarmer.Status')),
            ],
        ),
    ]
