# Generated by Django 3.0.3 on 2020-03-06 12:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('call', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mill',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('lat', models.FloatField(blank=True, null=True, unique=True)),
                ('lng', models.FloatField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ownermill',
            fields=[
                ('oid', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False)),
                ('queue', models.IntegerField(blank=True, null=True)),
                ('farmer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wakerfarmer.Farmer')),
                ('mill', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wakerfarmer.Mill')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('sprice', models.IntegerField(blank=True, null=True)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('farmer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wakerfarmer.Farmer')),
                ('mill', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wakerfarmer.Mill')),
            ],
        ),
        migrations.AddField(
            model_name='mill',
            name='ownermill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wakerfarmer.Ownermill'),
        ),
    ]
