# Generated by Django 2.1.13 on 2019-12-03 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wakerfarmer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mill',
            name='lat',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mill',
            name='lng',
            field=models.CharField(default='', max_length=100),
        ),
    ]
