# Generated by Django 2.2.7 on 2020-01-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wakerfarmer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
