# Generated by Django 3.0.4 on 2020-03-12 10:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wakerfarmer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
