# Generated by Django 2.2.7 on 2019-12-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wakerfarmer', '0002_auto_20191203_0457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('call', models.IntegerField()),
            ],
        ),
    ]
