# Generated by Django 2.2.7 on 2019-12-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wakerfarmer', '0004_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('lid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Usertype',
            fields=[
                ('urid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='mill',
            name='sprice',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='mill',
            name='lat',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='mill',
            name='lng',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='mill',
            name='price',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='mill',
            name='score',
            field=models.IntegerField(default=None),
        ),
    ]
