# Generated by Django 2.2.7 on 2019-12-14 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wakerfarmer', '0005_auto_20191214_1852'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Usertype',
        ),
    ]
