# Generated by Django 2.2.7 on 2019-12-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wakerfarmer', '0006_auto_20191214_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='call',
            field=models.IntegerField(default=None),
        ),
    ]
