# Generated by Django 2.2.7 on 2019-12-14 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wakerfarmer', '0007_auto_20191214_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mill',
            old_name='sprice',
            new_name='prices',
        ),
    ]
