# Generated by Django 2.2.7 on 2019-12-14 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wakerfarmer', '0008_auto_20191214_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mill',
            old_name='prices',
            new_name='_prices',
        ),
    ]
