# Generated by Django 2.2.7 on 2019-12-14 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wakerfarmer', '0009_auto_20191214_2030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mill',
            old_name='_prices',
            new_name='sprice',
        ),
    ]
