# Generated by Django 2.2.7 on 2019-12-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wakerfarmer', '0010_auto_20191214_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mill',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mill',
            name='sprice',
            field=models.IntegerField(),
        ),
    ]
