# Generated by Django 2.2.7 on 2019-12-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wakerfarmer', '0011_auto_20191214_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mill',
            name='score',
            field=models.IntegerField(),
        ),
    ]
