# Generated by Django 2.2.7 on 2019-12-14 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wakerfarmer', '0012_auto_20191214_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mill',
            name='sprice',
        ),
    ]
