# Generated by Django 2.2.7 on 2019-12-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wakerfarmer', '0013_remove_mill_sprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='mill',
            name='sprice',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='call',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mill',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mill',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
