# Generated by Django 2.2.7 on 2019-12-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wakerfarmer', '0014_auto_20191214_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='call',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mill',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mill',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mill',
            name='sprice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
